# Generated by Django 6.0 on 2025-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_prediction_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='role_type',
            field=models.IntegerField(default=1),
        ),
    ]
